name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Composer packages
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Make a Composer release
        # Assuming you've a script named "composer-release" in your composer.json.
        # If not, replace with appropriate command or script to make the release.
        run: composer composer-release

